import type { Platform, PlatformId, PlatformTheme } from "./types";

/**
 * Every colour the previews use lives here, so fidelity is a config change,
 * not a code change. The in-app "Colours" panel writes overrides on top of
 * these values (see lib/store.tsx), which is the fastest way to correct any
 * shade that looks off next to the real app on your phone.
 */

// WhatsApp's doodle wallpaper, approximated as a tiled inline SVG so it stays
// crisp and needs no network.
const waPattern = (dark: boolean) => {
  const stroke = dark ? "%231b2b33" : "%23d8cec3";
  const doodles =
    "%3Cpath d='M18 22c4-6 12-6 16 0M26 34v8'/%3E" +
    "%3Cpath d='M96 18l6 6-6 6-6-6z'/%3E" +
    "%3Ccircle cx='118' cy='44' r='7'/%3E" +
    "%3Cpath d='M12 92h16v12H18l-6 6z'/%3E" +
    "%3Cpath d='M62 66c0-6 5-10 11-10s11 4 11 10-5 10-11 10h-4l-7 6z'/%3E" +
    "%3Cpath d='M104 100l8-8 8 8-8 8z'/%3E" +
    "%3Cpath d='M44 118h14M51 111v14'/%3E" +
    "%3Ccircle cx='36' cy='66' r='5'/%3E" +
    "%3Cpath d='M80 124c3-4 9-4 12 0'/%3E";
  return (
    "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' " +
    "width='140' height='140' viewBox='0 0 140 140'%3E%3Cg fill='none' stroke='" +
    stroke +
    "' stroke-width='1.6' stroke-linecap='round'%3E" +
    doodles +
    "%3C/g%3E%3C/svg%3E\")"
  );
};

export const IG_GRADIENT =
  "linear-gradient(160deg,#3C5AFE 0%,#7B3FE4 58%,#B02BC0 100%)";
export const TINDER_GRADIENT =
  "linear-gradient(100deg,#FD267A 0%,#FF6036 100%)";

const platforms: Platform[] = [
  {
    id: "imessage",
    name: "iMessage",
    engine: "imessage",
    os: "ios",
    font: "sf",
    fontSize: 17,
    radius: 18,
    tightRadius: 6,
    maxWidth: 74,
    placeholder: "iMessage",
    headerStyle: "ios-center",
    readReceipt: "text",
    metaInBubble: false,
    tail: true,
    defaultDark: false,
    light: {
      bg: "#FFFFFF",
      headerBg: "rgba(248,248,248,0.92)",
      headerFg: "#000000",
      headerSub: "#8E8E93",
      border: "rgba(0,0,0,0.16)",
      out: "#248BF5",
      outFg: "#FFFFFF",
      in: "#E9E9EB",
      inFg: "#000000",
      accent: "#007AFF",
      meta: "#8E8E93",
      metaOut: "#8E8E93",
      tick: "#8E8E93",
      barBg: "rgba(248,248,248,0.92)",
      inputBg: "#FFFFFF",
      inputFg: "#000000",
      inputBorder: "#C9C9CE",
      avatarBg: "#C7C7CC",
    },
    dark: {
      bg: "#000000",
      headerBg: "rgba(26,26,26,0.88)",
      headerFg: "#FFFFFF",
      headerSub: "#8E8E93",
      border: "rgba(255,255,255,0.16)",
      out: "#248BF5",
      outFg: "#FFFFFF",
      in: "#26252A",
      inFg: "#FFFFFF",
      accent: "#0A84FF",
      meta: "#8E8E93",
      metaOut: "#8E8E93",
      tick: "#8E8E93",
      barBg: "rgba(26,26,26,0.88)",
      inputBg: "#000000",
      inputFg: "#FFFFFF",
      inputBorder: "#38383A",
      avatarBg: "#48484A",
    },
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    engine: "whatsapp",
    os: "ios",
    font: "sf",
    fontSize: 16,
    radius: 8,
    tightRadius: 8,
    maxWidth: 80,
    placeholder: "Message",
    headerStyle: "ios-center",
    readReceipt: "ticks",
    metaInBubble: true,
    tail: true,
    defaultDark: false,
    light: {
      bg: "#EFE5DD",
      bgPattern: waPattern(false),
      headerBg: "#F6F6F6",
      headerFg: "#000000",
      headerSub: "#667781",
      border: "rgba(0,0,0,0.12)",
      out: "#D9FDD3",
      outFg: "#111B21",
      in: "#FFFFFF",
      inFg: "#111B21",
      accent: "#00A884",
      meta: "#667781",
      metaOut: "#5B806A",
      tick: "#53BDEB",
      barBg: "#F6F6F6",
      inputBg: "#FFFFFF",
      inputFg: "#111B21",
      inputBorder: "#E3E3E3",
      avatarBg: "#CFD9DE",
    },
    dark: {
      bg: "#0B141A",
      bgPattern: waPattern(true),
      headerBg: "#1F2C34",
      headerFg: "#E9EDEF",
      headerSub: "#8696A0",
      border: "rgba(255,255,255,0.10)",
      out: "#005C4B",
      outFg: "#E9EDEF",
      in: "#1F2C34",
      inFg: "#E9EDEF",
      accent: "#00A884",
      meta: "#8696A0",
      metaOut: "#9BC4B4",
      tick: "#53BDEB",
      barBg: "#1F2C34",
      inputBg: "#2A3942",
      inputFg: "#E9EDEF",
      inputBorder: "#2A3942",
      avatarBg: "#3B4A54",
    },
  },
  {
    id: "instagram",
    name: "Instagram",
    engine: "instagram",
    os: "ios",
    font: "sf",
    fontSize: 15,
    radius: 22,
    tightRadius: 6,
    maxWidth: 74,
    placeholder: "Message...",
    headerStyle: "instagram",
    readReceipt: "text",
    metaInBubble: false,
    tail: false,
    defaultDark: true,
    light: {
      bg: "#FFFFFF",
      headerBg: "#FFFFFF",
      headerFg: "#000000",
      headerSub: "#737373",
      border: "#DBDBDB",
      out: IG_GRADIENT,
      outFg: "#FFFFFF",
      in: "#EFEFEF",
      inFg: "#000000",
      accent: "#0095F6",
      meta: "#737373",
      metaOut: "#737373",
      tick: "#737373",
      barBg: "#FFFFFF",
      inputBg: "#FFFFFF",
      inputFg: "#000000",
      inputBorder: "#DBDBDB",
      avatarBg: "#DBDBDB",
    },
    dark: {
      bg: "#000000",
      headerBg: "#000000",
      headerFg: "#FFFFFF",
      headerSub: "#A8A8A8",
      border: "#262626",
      out: IG_GRADIENT,
      outFg: "#FFFFFF",
      in: "#262626",
      inFg: "#FFFFFF",
      accent: "#0095F6",
      meta: "#A8A8A8",
      metaOut: "#A8A8A8",
      tick: "#A8A8A8",
      barBg: "#000000",
      inputBg: "#000000",
      inputFg: "#FFFFFF",
      inputBorder: "#363636",
      avatarBg: "#363636",
    },
  },
  {
    id: "hinge",
    name: "Hinge",
    engine: "hinge",
    os: "ios",
    font: "serif",
    fontSize: 16,
    radius: 20,
    tightRadius: 8,
    maxWidth: 76,
    placeholder: "Message",
    headerStyle: "hinge",
    readReceipt: "none",
    metaInBubble: false,
    tail: false,
    defaultDark: false,
    light: {
      bg: "#FFFFFF",
      headerBg: "#FFFFFF",
      headerFg: "#16182B",
      headerSub: "#6E7191",
      border: "#E7E7EC",
      out: "#E8E1F6",
      outFg: "#16182B",
      in: "#F2F2F5",
      inFg: "#16182B",
      accent: "#55286F",
      meta: "#8E8EA0",
      metaOut: "#8E8EA0",
      tick: "#8E8EA0",
      barBg: "#FFFFFF",
      inputBg: "#F2F2F5",
      inputFg: "#16182B",
      inputBorder: "#E7E7EC",
      avatarBg: "#E0DAEE",
    },
    dark: {
      bg: "#16182B",
      headerBg: "#16182B",
      headerFg: "#FFFFFF",
      headerSub: "#A0A3BD",
      border: "#2A2D45",
      out: "#4B2E6B",
      outFg: "#FFFFFF",
      in: "#25283F",
      inFg: "#FFFFFF",
      accent: "#B08CD9",
      meta: "#A0A3BD",
      metaOut: "#C9BCDD",
      tick: "#A0A3BD",
      barBg: "#16182B",
      inputBg: "#25283F",
      inputFg: "#FFFFFF",
      inputBorder: "#2A2D45",
      avatarBg: "#3A2E4F",
    },
  },
  {
    id: "telegram",
    name: "Telegram",
    engine: "bubble",
    os: "ios",
    font: "sf",
    fontSize: 16,
    radius: 14,
    tightRadius: 6,
    maxWidth: 78,
    placeholder: "Message",
    headerStyle: "ios-center",
    readReceipt: "ticks",
    metaInBubble: true,
    tail: true,
    defaultDark: false,
    light: {
      bg: "#E4EDF6",
      bgPattern:
        "radial-gradient(circle at 18% 18%, rgba(255,255,255,0.6), transparent 45%), radial-gradient(circle at 82% 72%, rgba(160,195,230,0.5), transparent 45%)",
      headerBg: "#F7F7F7",
      headerFg: "#000000",
      headerSub: "#8E8E93",
      border: "rgba(0,0,0,0.12)",
      out: "#EFFDDE",
      outFg: "#000000",
      in: "#FFFFFF",
      inFg: "#000000",
      accent: "#3390EC",
      meta: "#A1AAB3",
      metaOut: "#6BAF6B",
      tick: "#4FAE4E",
      barBg: "#F7F7F7",
      inputBg: "#FFFFFF",
      inputFg: "#000000",
      inputBorder: "#DADCE0",
      avatarBg: "#B0C4DE",
    },
    dark: {
      bg: "#0E1621",
      headerBg: "#17212B",
      headerFg: "#FFFFFF",
      headerSub: "#7D8B99",
      border: "rgba(255,255,255,0.08)",
      out: "#2B5278",
      outFg: "#FFFFFF",
      in: "#182533",
      inFg: "#FFFFFF",
      accent: "#5288C1",
      meta: "#7D8B99",
      metaOut: "#8DB2D9",
      tick: "#61B6EC",
      barBg: "#17212B",
      inputBg: "#182533",
      inputFg: "#FFFFFF",
      inputBorder: "#182533",
      avatarBg: "#2B5278",
    },
  },
  {
    id: "messenger",
    name: "Messenger",
    engine: "bubble",
    os: "ios",
    font: "sf",
    fontSize: 16,
    radius: 18,
    tightRadius: 5,
    maxWidth: 72,
    placeholder: "Aa",
    headerStyle: "ios-center",
    readReceipt: "avatar",
    metaInBubble: false,
    tail: false,
    defaultDark: false,
    light: {
      bg: "#FFFFFF",
      headerBg: "#FFFFFF",
      headerFg: "#050505",
      headerSub: "#65676B",
      border: "#E4E6EB",
      out: "#0A7CFF",
      outFg: "#FFFFFF",
      in: "#E4E6EB",
      inFg: "#050505",
      accent: "#0A7CFF",
      meta: "#65676B",
      metaOut: "#65676B",
      tick: "#0A7CFF",
      barBg: "#FFFFFF",
      inputBg: "#F0F2F5",
      inputFg: "#050505",
      inputBorder: "#F0F2F5",
      avatarBg: "#D8DADF",
    },
    dark: {
      bg: "#000000",
      headerBg: "#000000",
      headerFg: "#E4E6EB",
      headerSub: "#B0B3B8",
      border: "#1C1E21",
      out: "#0A7CFF",
      outFg: "#FFFFFF",
      in: "#303030",
      inFg: "#E4E6EB",
      accent: "#0A7CFF",
      meta: "#B0B3B8",
      metaOut: "#B0B3B8",
      tick: "#0A7CFF",
      barBg: "#000000",
      inputBg: "#303030",
      inputFg: "#E4E6EB",
      inputBorder: "#303030",
      avatarBg: "#3A3B3C",
    },
  },
  {
    id: "sms",
    name: "Google Messages",
    engine: "bubble",
    os: "android",
    font: "roboto",
    fontSize: 16,
    radius: 20,
    tightRadius: 6,
    maxWidth: 76,
    placeholder: "Text message",
    headerStyle: "android-left",
    readReceipt: "text",
    metaInBubble: false,
    tail: false,
    defaultDark: false,
    light: {
      bg: "#FFFFFF",
      headerBg: "#FFFFFF",
      headerFg: "#1F1F1F",
      headerSub: "#5F6368",
      border: "#E3E3E3",
      out: "#0B57D0",
      outFg: "#FFFFFF",
      in: "#E8EAED",
      inFg: "#1F1F1F",
      accent: "#0B57D0",
      meta: "#5F6368",
      metaOut: "#5F6368",
      tick: "#0B57D0",
      barBg: "#FFFFFF",
      inputBg: "#F1F3F4",
      inputFg: "#1F1F1F",
      inputBorder: "#F1F3F4",
      avatarBg: "#C2E7FF",
    },
    dark: {
      bg: "#131314",
      headerBg: "#131314",
      headerFg: "#E3E3E3",
      headerSub: "#9AA0A6",
      border: "#2E2F31",
      out: "#004A77",
      outFg: "#C2E7FF",
      in: "#1F1F1F",
      inFg: "#E3E3E3",
      accent: "#A8C7FA",
      meta: "#9AA0A6",
      metaOut: "#9AA0A6",
      tick: "#A8C7FA",
      barBg: "#131314",
      inputBg: "#1F1F1F",
      inputFg: "#E3E3E3",
      inputBorder: "#1F1F1F",
      avatarBg: "#004A77",
    },
  },
  {
    id: "tinder",
    name: "Tinder",
    engine: "bubble",
    os: "ios",
    font: "sf",
    fontSize: 16,
    radius: 20,
    tightRadius: 8,
    maxWidth: 74,
    placeholder: "Type a message",
    headerStyle: "hinge",
    readReceipt: "none",
    metaInBubble: false,
    tail: false,
    defaultDark: false,
    light: {
      bg: "#FFFFFF",
      headerBg: "#FFFFFF",
      headerFg: "#000000",
      headerSub: "#8C8C8C",
      border: "#EBEBEB",
      out: TINDER_GRADIENT,
      outFg: "#FFFFFF",
      in: "#F1F1F1",
      inFg: "#000000",
      accent: "#FD267A",
      meta: "#8C8C8C",
      metaOut: "#8C8C8C",
      tick: "#8C8C8C",
      barBg: "#FFFFFF",
      inputBg: "#F1F1F1",
      inputFg: "#000000",
      inputBorder: "#EBEBEB",
      avatarBg: "#F1D6DE",
    },
    dark: {
      bg: "#121212",
      headerBg: "#121212",
      headerFg: "#FFFFFF",
      headerSub: "#A0A0A0",
      border: "#242424",
      out: TINDER_GRADIENT,
      outFg: "#FFFFFF",
      in: "#242424",
      inFg: "#FFFFFF",
      accent: "#FD267A",
      meta: "#A0A0A0",
      metaOut: "#A0A0A0",
      tick: "#A0A0A0",
      barBg: "#121212",
      inputBg: "#242424",
      inputFg: "#FFFFFF",
      inputBorder: "#242424",
      avatarBg: "#3A2029",
    },
  },
  {
    id: "discord",
    name: "Discord",
    engine: "discord",
    os: "ios",
    font: "sf",
    fontSize: 16,
    radius: 8,
    tightRadius: 8,
    maxWidth: 100,
    placeholder: "Message",
    headerStyle: "discord",
    readReceipt: "none",
    metaInBubble: false,
    tail: false,
    defaultDark: true,
    light: {
      bg: "#FFFFFF",
      headerBg: "#F2F3F5",
      headerFg: "#060607",
      headerSub: "#4E5058",
      border: "#E3E5E8",
      out: "transparent",
      outFg: "#313338",
      in: "transparent",
      inFg: "#313338",
      accent: "#5865F2",
      meta: "#5C5E66",
      metaOut: "#5C5E66",
      tick: "#5865F2",
      barBg: "#FFFFFF",
      inputBg: "#EBEDEF",
      inputFg: "#313338",
      inputBorder: "#EBEDEF",
      avatarBg: "#5865F2",
    },
    dark: {
      bg: "#313338",
      headerBg: "#313338",
      headerFg: "#F2F3F5",
      headerSub: "#B5BAC1",
      border: "#26282C",
      out: "transparent",
      outFg: "#DBDEE1",
      in: "transparent",
      inFg: "#DBDEE1",
      accent: "#5865F2",
      meta: "#949BA4",
      metaOut: "#949BA4",
      tick: "#5865F2",
      barBg: "#313338",
      inputBg: "#383A40",
      inputFg: "#DBDEE1",
      inputBorder: "#383A40",
      avatarBg: "#5865F2",
    },
  },
];

export const PLATFORMS = platforms;

export const PLATFORM_MAP = Object.fromEntries(
  platforms.map((p) => [p.id, p])
) as Record<PlatformId, Platform>;

export function getPlatform(id: PlatformId): Platform {
  return PLATFORM_MAP[id] ?? PLATFORM_MAP.imessage;
}

/** Keys exposed in the colour tuner, in display order. */
export const TUNABLE_KEYS: (keyof PlatformTheme)[] = [
  "bg",
  "out",
  "outFg",
  "in",
  "inFg",
  "headerBg",
  "headerFg",
  "accent",
  "meta",
  "barBg",
  "inputBg",
];

export const THEME_LABELS: Partial<Record<keyof PlatformTheme, string>> = {
  bg: "Chat background",
  out: "Your bubble",
  outFg: "Your text",
  in: "Their bubble",
  inFg: "Their text",
  headerBg: "Header",
  headerFg: "Header text",
  accent: "Accent / send",
  meta: "Timestamps",
  barBg: "Input bar",
  inputBg: "Input field",
};
